### ISSUE TITLE
Bug: Numbering is broken when using manual splitter

### ISSUE THREAD

**Issue by aarohmankad** [kossnocorp/chirrapp#6]
From a comment on HN, see this image for reproduction:

![image](https://user-images.githubusercontent.com/3311321/29838112-0eb1e1fc-8caf-11e7-8363-57817e0cf06a.png)

**Comment by kossnocorp** [comment]
Thank you for reporting!

**Comment by kossnocorp** [comment]
Now it's fixed at deployed.
